# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping-pong.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fping-pong.proto\x12\x1c\x63om.tananushka.grpcdemo.grpc\"\x17\n\x04Ping\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x17\n\x04Pong\x12\x0f\n\x07message\x18\x01 \x01(\t2g\n\x0fPingPongService\x12T\n\x08PingPong\x12\".com.tananushka.grpcdemo.grpc.Ping\x1a\".com.tananushka.grpcdemo.grpc.Pong\"\x00\x42 \n\x1c\x63om.tananushka.grpcdemo.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping_pong_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.tananushka.grpcdemo.grpcP\001'
  _globals['_PING']._serialized_start=49
  _globals['_PING']._serialized_end=72
  _globals['_PONG']._serialized_start=74
  _globals['_PONG']._serialized_end=97
  _globals['_PINGPONGSERVICE']._serialized_start=99
  _globals['_PINGPONGSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
